[context.production]
  [context.production.environment]
    HUGO_BASEURL = "https://hugo-mwe.netlify.com/"

[context.branch-deploy]
  command = "hugo --baseURL ${DEPLOY_PRIME_URL}/"

[context.deploy-preview]
  command = "hugo --baseURL ${DEPLOY_PRIME_URL}/"
