[context.production]
  command = "HUGOxPARAMSxGITxBRANCH=${BRANCH} hugo --baseURL https://site.basa.casa"

[context.branch-deploy]
  command = "HUGOxPARAMSxGITxBRANCH=${BRANCH} hugo --baseURL ${DEPLOY_PRIME_URL}/"

[context.deploy-preview]
  command = "hugo --baseURL ${DEPLOY_PRIME_URL}/"
